### 异常处理
python中的异常处理需要使用try..except语句。基本的形式如下：

```python
try:
    # 语句
except:
    # 捕获异常
finally:
    # 语句
```
其中，except语句可以有多个，用于捕获不同类型的异常操作。如：

```python
try:
    f = open('test.txt')
except NameError:
    print 'NameError'
except FileNotFoundError:
    print 'FileNotFoundError'
```

python2也可以写成下面的这种形式。

```python
try:
    f = open('test.txt')
except IOError, FileNotFoundError:
    print 'error'
```

python3中需要写成下面的这种格式：

```python
try:
    f = open('test.txt')
except (NameError, FileNotFoundError):
    # 上面的需要写成元组的形式
    print 'error'
```

我们也可以设置一个处理未捕获所有异常的except。

```python
try:
    f = open('test.txt')
except (NameError, FileNotFoundError):
    # 上面的需要写成元组的形式
    print 'error'
except Exception:
    # 用于捕获上面所有的except都没有捕获的异常
```

except也可以使用else进行搭配，在没有异常发生的时候才会执行的功能。

```python
try:
    f = open('test.txt')
except (NameError, FileNotFoundError):
    # 上面的需要写成元组的形式
    print 'error'
except Exception:
    # 用于捕获上面所有的except都没有捕获的异常
else:
    # 这里的语句在没有异常发生的时候才会执行
```

finally语句不管有没有异常发生都会之行其中所包含的语句。

```python
try:
    f = open('test.txt')
except (NameError, FileNotFoundError):
    # 上面的需要写成元组的形式
    print 'error'
except Exception:
    # 用于捕获上面所有的except都没有捕获的异常
finally:
    # 不管有没有异常发生，其中的语句都会发生
```

> 抛出异常

python中我们可以使用raise语句来抛出异常。raise不仅能够抛出系统异常，也可以抛出自定义异常。

```python
try:
    open('test.txt')
except Exception as e:
    # 接着抛出异常
    raise e
```

> 自定义异常

python中所有的异常类都继承自Exception这个基类。我们可以在自定义异常类中定义我们自己的属性和方法。如：

```python
class MustBeNumber(Exception):
    def __init__(self, msg):
        self.error_message = msg

def get_num():
    try:
        num = raw_input('请输入数字：')
        if not num.isdigit():
            # 不满足条件，抛出自定义异常
            raise MustBeNumber('输入的必须是数字')
    except MustBeNumber as e:
        # 这个e就是MustBeNumber的一个实例
        print('The Error Message: %s' % e.error_message)

get_num()

# 输入一个非纯数字的字符串，会得到如下的错误
# The Error Message: 输入的必须是数字
```